spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.24.51:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xxcwl0304
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 0
    host: 39.106.24.51
    port: 6381
    password:
    jedis:
      pool:
        max-wait: 200
        max-idle: 10
        min-idle: 0
    timeout: 1000
  messages:
    basename: i18n.messages/messages
    encoding: GBK
mconfig:
  swagger-ui-open: true
