spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.24.51:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xxcwl0304
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 0
    host: 39.106.24.51
    port: 6382
    password:
    jedis:
      pool:
        max-wait: 200
        max-idle: 10
        min-idle: 0
    timeout: 1000
  messages:
    basename: i18n.messages/messages
    encoding: GBK
  kafka:
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      client-id: test-hello-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test-hello-group
    bootstrap-servers: 39.106.24.51:9092
mconfig:
  swagger-ui-open: true

debug: true


